### ISSUE TITLE
Missing mods + incorrect values.

### ISSUE THREAD

**Issue by buczbucz** [KloppstockBw/GFNPoEPriceCheck#10]
It works in general, but for most items I get missing mods or mods with incorrect values.
For example:

Item:
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/dfdd2fbd-eb45-4973-a36f-2bcfcfab8149)

Google doc:
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/9371847f-06ea-42a5-bd19-3537d092f315)

Awakened POE:
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/265148c9-b100-4e61-a967-a480eade62e3)

However price prediction seems to catch all the mods?

![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/315e3b93-fcf9-4207-bfb8-fa99dfec008a)

**Comment by buczbucz** [comment]
Another example:

Item:
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/4d9e655a-61fa-4a0c-bc08-862d77bc0c4d)

Google doc:
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/d1f4162d-3dd5-49d7-bcbf-c5e098835b8e)

Awakened POE:
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/a2097846-8a92-4aca-a439-da01945656b9)

It skipped last resistance mod.

**Comment by buczbucz** [comment]
Any ideas?

**Comment by KloppstockBw** [comment]
No idea tbh. Have it on German too and everything is correct. Can you please do price check and the Ctrl V to notepad and provide the data? Would like to see what is handed over to awakened

**Comment by buczbucz** [comment]
```
Item Class: Quivers
Rarity: Rare
Honour Skewer
Heavy Arrow Quiver
--------
Requirements:
Level: 61
--------
Item Level: 71
--------
{ Implicit Modifier — Damage, Physical, Attack }
Adds 15(12-15) to 24(24-27) Physical Damage to Attacks (implicit)
--------
{ Prefix Modifier "Buzzing" (Tier: 8) — Damage, Elemental, Lightning, Attack }
Adds 2 to 16(16-18) Lightning Damage to Attacks
{ Prefix Modifier "Rotund" (Tier: 4) — Life }
+60(60-69) to maximum Life
{ Suffix Modifier "of Flight" (Tier: 4) — Speed }
25(18-25)% increased Projectile Speed
{ Suffix Modifier "of Rage" (Tier: 4) — Damage, Attack, Critical }
+24(20-24)% to Critical Strike Multiplier with Bows
```

**Comment by buczbucz** [comment]
I tried ctrl+d those items locally (so poe running on my steam, not via gfn) and got this:

![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/03347069-8488-485a-b7e8-fd82b50e0041)
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/2a638c9a-4783-432e-b92a-6bb8c16aa92e)

**Comment by buczbucz** [comment]
In both cases it's missing the last mod on the item.

**Comment by KloppstockBw** [comment]
So it's an awakened issue not my script?

**Comment by buczbucz** [comment]
Nah, you can see in awakened it's showing that last stat:

+24(20-24)% to Critical Strike Multiplier with Bows
and
+32(30-35)% to Lightning Resistance

**Comment by KloppstockBw** [comment]
Alright, let me test

**Comment by buczbucz** [comment]
In that google doc there are some extra empty lines at the bottom, but if I just copy the text (skipping the empty lines) to awakened poe trade (open in browser option) then it show all stats. So the copying works fine, but there is some error with pasting it automatically to awakened poe trade.

**Comment by buczbucz** [comment]
I think I figured it out.

When I press F6 with your script it's copying the item without a single empty line at the bottom.
When I press ctrl-alt-c in my local game on Steam (not gfn), the text is the same but there is an empty line at the bottom.

If I copy the result of F6 to awakened poe trade (open in browser option) it skips last mod.
If I copy the result of ctrl-alt-c or manually add that missing empty line then it shows all mods.

This:
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/721c7543-a0c5-4077-a71f-a510f8b645e7)
vs this:
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/0bb9fb82-e88e-42a4-96bf-0cf2e2e1328c)

**Comment by KloppstockBw** [comment]
Oh okay. Removed that line in last update and so far no one complained about it. I test and let you know

**Comment by buczbucz** [comment]
Cheers!

**Comment by KloppstockBw** [comment]
Kind ist krank und somit bin ich immer noch lvl 35 und keine Zeit für PC. Voll kacke xD

**Comment by buczbucz** [comment]
I don't speak German so I google translated. :P Hope your kid gets better and you get some gaming time. This league is really fun so far. :)

**Comment by KloppstockBw** [comment]
Oh thought so because your Google doc screenshot is German : D
Please test this :
https://github.com/KloppstockBw/GFNPoEPriceCheck/blob/main/Testlineempty.au3

**Comment by buczbucz** [comment]
That's probably because my GFN server is located in Germany (EU Central).
Tested it:

![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/bc70871b-3fce-42b2-beb3-c171b110f9e8)

It shows all mods but now it copies 3 empty lines, so there are 2 unrecognized modifier "errors" at the bottom, which I can live with tbh.

**Comment by buczbucz** [comment]
![image](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/31707119/aa75008e-9cd7-4fd6-8f7d-c0a100307b97)

Same for helmet.

**Comment by KloppstockBw** [comment]
Nah it looks stupid. Did an update you can test it again and now it should be fixed

**Comment by buczbucz** [comment]
It works like a charm now.

Thank you!

**Comment by KloppstockBw** [comment]
Thanks for testing and have fun
