### ISSUE TITLE
No inputs from script

### ISSUE THREAD

**Issue by GenKoc** [KloppstockBw/GFNPoEPriceCheck#14]
Hi. Made all by instruction, but script didnt paste anything
Manually it pasting to Steam Browser([Google Doc](https://docs.google.com/document/d/1kK9ecm9mnvR3hVNHLdio-zufVgeMPlF6Inh9jAscAI4/edit?usp=drive_web&ouid=114012999847268379212)) 
Playing on Russian version(in poe Trade in settinge lang = rus) 
![photo_2023-12-20_12-12-01](https://github.com/KloppstockBw/GFNPoEPriceCheck/assets/30290724/872266db-b782-4702-b7ad-057b8e74fa06)

**Comment by KloppstockBw** [comment]
Russian is not supported. English oy
