### ISSUE TITLE
Autoit error

### ISSUE THREAD

**Issue by redrush1213** [KloppstockBw/GFNPoEPriceCheck#18]
![error](https://github.com/user-attachments/assets/dcd7ca23-e9dd-4803-8b63-2ffcdcb94417)

**Comment by KloppstockBw** [comment]
Hm. Strange, I had no issues. Let me check

**Comment by Yuukidge** [comment]
I have the same problem. It appears when I try to paste a google document url.

**Comment by redrush1213** [comment]
Yes, error after paste url.

**Comment by KloppstockBw** [comment]
Did a rollback. Probably i use another language before doing another update

**Comment by KloppstockBw** [comment]
Can you please check if the beta i just uploaded is working fine?

**Comment by Yuukidge** [comment]
> Can you please check if the beta i just uploaded is working fine?

Beta is working good.

**Comment by KloppstockBw** [comment]
Thought so. I accidently put a f in the middle of code. Thanks guys
