### ISSUE TITLE
don't write to google docs

### ISSUE THREAD

**Issue by hosaka86** [KloppstockBw/GFNPoEPriceCheck#9]
Hi,

I've setup everyting as you did in the video but i get the error to check if everyone could write to that file. The Browser in Steam does not open automaticly. If i open it (I've set the startpage as I should) manual i can paste the item details by hand. But it does not work as expected for some reason.

This is the config so you can check the file is named POE and writeable by anyone (as I said i can do it manualy in the steam browser on GFN without problem)

[HotKey]
Key1={F7}
Key2={F6}
Key3={F5}
Key4={F9}
Key5={F11}
[AwakenedPath]
ExePath=C:\Users\anmel\AppData\Local\Programs\Awakened PoE Trade\Awakened PoE Trade.exe
[AwakenedPasteWindow]
Koordinaten=199,111
[docsGoogleURL]
URL=deleted_for_problem_solved
[Setup Done]
Status=1

**Comment by KloppstockBw** [comment]
Does the script work when you enter item details manually into the docs inside GFN? I see that it's empty right now. You need to press Ctrl ALT C, then Ctrl V in docs and then run macro

**Comment by hosaka86** [comment]
If I open the browser myself (F7, click on Steam browser) and manually copy the details from the clipboard into the google doc and then execute the script, the transfer to AwakenPoE works. However, when I hover an item in the inventory and press F6, only the white window appears that tells me to press F6 again when the details are in the Google Doc. In your video, the Steam browser starts automatically. This is not the case for me. I have set Fullscreen, maybe I have to select windowed Fullscreen?

**Comment by hosaka86** [comment]
I found out what the problem was. You have to call up the Steam overlay yourself (F7), open the browser and then press F7 again so that the browser is open in the background. Then it also works from the inventory. A bit tricky, but maybe the description will help others who have similar starting difficulties. 

Thank you very much for the great idea, the implementation and your quick response. Really great! Thank you!

**Comment by KloppstockBw** [comment]
Thanks. I try to update the instruction
